server:
  port: 8080

config-attributes:
  database: 114.116.221.53

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${config-attributes.database}:3306/project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Cyt123456!
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      connection-test-query: SELECT 1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: team.pi.demo.pojo