server:
  port: 8080

config-attributes:
#   database: 127.0.0.1
  database: 114.116.221.53

spring:
  redis:
    database: 0
    host: ${config-attributes.database}         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password:               # Redis服务器连接密码（默认为空）
    pool:
      max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10          # 连接池中的最大空闲连接
      max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0           # 连接池中的最小空闲连接
    timeout: 1000           # 连接超时时间（毫秒）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${config-attributes.database}:3306/project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
#    password: Cyt123456!
    password: 159357
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      connection-test-query: SELECT 1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: team.pi.demo.pojo